language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Encryption.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.Encryption.sln
  - dotnet restore
  - dotnet test Encryption.Test/Encryption.Test.csproj
